//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment_Room_Schedule
    {
        public int Appointment_ID { get; set; }
        public Nullable<int> Room_ID { get; set; }
        public Nullable<int> Member_ID { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<int> Doctor_ID { get; set; }
        public Nullable<int> Nurse_ID { get; set; }
    
        public virtual Member_EmployeeList Member_EmployeeList { get; set; }
        public virtual Member_EmployeeList Member_EmployeeList1 { get; set; }
        public virtual Member_MemberList Member_MemberList { get; set; }
        public virtual RoomList RoomList { get; set; }
    }
}
