//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appt_ClinicList
    {
        public int ClinicList_ID { get; set; }
        public int Clinic_ID { get; set; }
        public int ClinicNumber { get; set; }
        public int Member_ID { get; set; }
        public int PatientState_ID { get; set; }
        public bool IsCancelled { get; set; }
        public bool IsVIP { get; set; }
    
        public virtual Member_MemberList Member_MemberList { get; set; }
        public virtual Schedule_ClinicInfo Schedule_ClinicInfo { get; set; }
        public virtual Appt_PatientState_Ref Appt_PatientState_Ref { get; set; }
    }
}
