//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_tExpenseRequests
    {
        public int fRequestID { get; set; }
        public int fEmployeeID { get; set; }
        public int fExpenseTypeID { get; set; }
        public Nullable<decimal> fAmount { get; set; }
        public Nullable<System.DateTime> fRequestDate { get; set; }
        public Nullable<System.DateTime> fExpenseDate { get; set; }
        public string fRequestsDescription { get; set; }
        public string fApprovalStatus { get; set; }
        public string fPayStatus { get; set; }
    
        public virtual Member_EmployeeList Member_EmployeeList { get; set; }
        public virtual Attendance_tExpenseTypes Attendance_tExpenseTypes { get; set; }
    }
}
