//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cases_NewBornList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cases_NewBornList()
        {
            this.Member_Care = new HashSet<Member_Care>();
        }
    
        public int Member_ID { get; set; }
        public int NewBorn_ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public bool Gender { get; set; }
        public string Blood_Type { get; set; }
        public string ICE_Name { get; set; }
        public string ICE_Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member_Care> Member_Care { get; set; }
        public virtual Member_MemberList Member_MemberList { get; set; }
    }
}
