//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cases_MainCase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cases_MainCase()
        {
            this.Cases_Medical_Records = new HashSet<Cases_Medical_Records>();
            this.Cases_Prescription = new HashSet<Cases_Prescription>();
            this.Cases_TestReport = new HashSet<Cases_TestReport>();
        }
    
        public int Case_ID { get; set; }
        public int Member_ID { get; set; }
        public string PastHistory { get; set; }
        public string AllergyRecord { get; set; }
        public string Firstvisit_Date { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Attachment { get; set; }
    
        public virtual Member_MemberList Member_MemberList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cases_Medical_Records> Cases_Medical_Records { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cases_Prescription> Cases_Prescription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cases_TestReport> Cases_TestReport { get; set; }
    }
}
