//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cases_Prescriptionlist
    {
        public int Prescription_ID { get; set; }
        public int Drug_ID { get; set; }
        public int Days { get; set; }
        public int Total_Amount { get; set; }
    
        public virtual Cases_Prescription Cases_Prescription { get; set; }
        public virtual Pharmacy_tMedicinesList Pharmacy_tMedicinesList { get; set; }
    }
}
