//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicSysEntities : DbContext
    {
        public ClinicSysEntities()
            : base("name=ClinicSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment_Room_Schedule> Appointment_Room_Schedule { get; set; }
        public virtual DbSet<Appt_ClinicList> Appt_ClinicList { get; set; }
        public virtual DbSet<Appt_PatientState_Ref> Appt_PatientState_Ref { get; set; }
        public virtual DbSet<Attendance_tAttendance> Attendance_tAttendance { get; set; }
        public virtual DbSet<Attendance_tExpenseRequests> Attendance_tExpenseRequests { get; set; }
        public virtual DbSet<Attendance_tExpenseTypes> Attendance_tExpenseTypes { get; set; }
        public virtual DbSet<Attendance_tLeave> Attendance_tLeave { get; set; }
        public virtual DbSet<Attendance_tLeaveTypes> Attendance_tLeaveTypes { get; set; }
        public virtual DbSet<Cases_MainCase> Cases_MainCase { get; set; }
        public virtual DbSet<Cases_Medical_Records> Cases_Medical_Records { get; set; }
        public virtual DbSet<Cases_NewBornList> Cases_NewBornList { get; set; }
        public virtual DbSet<Cases_Prescription> Cases_Prescription { get; set; }
        public virtual DbSet<Cases_Prescriptionlist> Cases_Prescriptionlist { get; set; }
        public virtual DbSet<Cases_TestReport> Cases_TestReport { get; set; }
        public virtual DbSet<Member_Care> Member_Care { get; set; }
        public virtual DbSet<Member_EmployeeList> Member_EmployeeList { get; set; }
        public virtual DbSet<Member_MemberList> Member_MemberList { get; set; }
        public virtual DbSet<Pharmacy_tClinicalUseDetails> Pharmacy_tClinicalUseDetails { get; set; }
        public virtual DbSet<Pharmacy_tClinicalUseList> Pharmacy_tClinicalUseList { get; set; }
        public virtual DbSet<Pharmacy_tMedicinesList> Pharmacy_tMedicinesList { get; set; }
        public virtual DbSet<Pharmacy_tSideEffectDetails> Pharmacy_tSideEffectDetails { get; set; }
        public virtual DbSet<Pharmacy_tSideEffectList> Pharmacy_tSideEffectList { get; set; }
        public virtual DbSet<Pharmacy_tTypeDetails> Pharmacy_tTypeDetails { get; set; }
        public virtual DbSet<Pharmacy_tTypeList> Pharmacy_tTypeList { get; set; }
        public virtual DbSet<RoomList> RoomList { get; set; }
        public virtual DbSet<RoomTypeList> RoomTypeList { get; set; }
        public virtual DbSet<Schedule_ClinicInfo> Schedule_ClinicInfo { get; set; }
        public virtual DbSet<Schedule_ClinicSchedule> Schedule_ClinicSchedule { get; set; }
        public virtual DbSet<Schedule_ClinicTime> Schedule_ClinicTime { get; set; }
        public virtual DbSet<Schedule_NurseSchedule> Schedule_NurseSchedule { get; set; }
        public virtual DbSet<Schedule_PharmacistSchedule> Schedule_PharmacistSchedule { get; set; }
        public virtual DbSet<Schedule_Staff_PharmacistShiftsTime> Schedule_Staff_PharmacistShiftsTime { get; set; }
        public virtual DbSet<Schedule_StaffSchedule> Schedule_StaffSchedule { get; set; }
        public virtual DbSet<Schedule_WardNurseSchedule> Schedule_WardNurseSchedule { get; set; }
        public virtual DbSet<Schedule_WardShiftsTime> Schedule_WardShiftsTime { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tCart> tCart { get; set; }
        public virtual DbSet<tCoupon> tCoupon { get; set; }
        public virtual DbSet<tCouponWallet> tCouponWallet { get; set; }
        public virtual DbSet<tOrder> tOrder { get; set; }
        public virtual DbSet<tOrderDetail> tOrderDetail { get; set; }
        public virtual DbSet<tProduct> tProduct { get; set; }
    }
}
