//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MemberSysEntities : DbContext
    {
        public MemberSysEntities()
            : base("name=MemberSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Member_Care> Member_Care { get; set; }
        public virtual DbSet<Member_EmployeeList> Member_EmployeeList { get; set; }
        public virtual DbSet<Member_MemberList> Member_MemberList { get; set; }
    }
}
