//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_EmployeeList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member_EmployeeList()
        {
            this.Appointment_Room_Schedule = new HashSet<Appointment_Room_Schedule>();
            this.Attendance_tAttendance = new HashSet<Attendance_tAttendance>();
            this.Attendance_tExpenseRequests = new HashSet<Attendance_tExpenseRequests>();
            this.Attendance_tLeave = new HashSet<Attendance_tLeave>();
            this.Schedule_ClinicInfo = new HashSet<Schedule_ClinicInfo>();
            this.Schedule_ClinicSchedule = new HashSet<Schedule_ClinicSchedule>();
            this.Schedule_StaffSchedule = new HashSet<Schedule_StaffSchedule>();
            this.Schedule_WardNurseSchedule = new HashSet<Schedule_WardNurseSchedule>();
            this.Schedule_PharmacistSchedule = new HashSet<Schedule_PharmacistSchedule>();
            this.Schedule_NurseSchedule = new HashSet<Schedule_NurseSchedule>();
        }
    
        public int Emp_ID { get; set; }
        public int Staff_Number { get; set; }
        public string Name { get; set; }
        public bool Gender { get; set; }
        public string Blood_Type { get; set; }
        public string National_ID { get; set; }
        public string Address { get; set; }
        public string Contact_Address { get; set; }
        public string Phone { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Emp_Type { get; set; }
        public string Department { get; set; }
        public string Emp_Password { get; set; }
        public byte[] EmpPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment_Room_Schedule> Appointment_Room_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance_tAttendance> Attendance_tAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance_tExpenseRequests> Attendance_tExpenseRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance_tLeave> Attendance_tLeave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_ClinicInfo> Schedule_ClinicInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_ClinicSchedule> Schedule_ClinicSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_StaffSchedule> Schedule_StaffSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_WardNurseSchedule> Schedule_WardNurseSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_PharmacistSchedule> Schedule_PharmacistSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_NurseSchedule> Schedule_NurseSchedule { get; set; }
    }
}
