//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_MemberList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member_MemberList()
        {
            this.Appointment_Room_Schedule = new HashSet<Appointment_Room_Schedule>();
            this.Appt_ClinicList = new HashSet<Appt_ClinicList>();
            this.Cases_MainCase = new HashSet<Cases_MainCase>();
            this.Cases_NewBornList = new HashSet<Cases_NewBornList>();
            this.tCart = new HashSet<tCart>();
            this.tOrder = new HashSet<tOrder>();
            this.tCouponWallet = new HashSet<tCouponWallet>();
        }
    
        public int Member_ID { get; set; }
        public int Member_Number { get; set; }
        public string Name { get; set; }
        public bool Gender { get; set; }
        public string Blood_Type { get; set; }
        public string National_ID { get; set; }
        public string Address { get; set; }
        public string Contact_Address { get; set; }
        public string Phone { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string ICE_Name { get; set; }
        public string ICE_Number { get; set; }
        public string Mem_Password { get; set; }
        public string Mem_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment_Room_Schedule> Appointment_Room_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appt_ClinicList> Appt_ClinicList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cases_MainCase> Cases_MainCase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cases_NewBornList> Cases_NewBornList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCart> tCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrder> tOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCouponWallet> tCouponWallet { get; set; }
    }
}
