//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Care
    {
        public int NewBorn_ID { get; set; }
        public int Care_ID { get; set; }
        public System.DateTime Care_Date { get; set; }
        public string Record_Type { get; set; }
        public string Record_dcp { get; set; }
    
        public virtual Cases_NewBornList Cases_NewBornList { get; set; }
    }
}
