//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacy_tClinicalUseList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pharmacy_tClinicalUseList()
        {
            this.Pharmacy_tClinicalUseDetails = new HashSet<Pharmacy_tClinicalUseDetails>();
        }
    
        public int fId_ClinicalUse { get; set; }
        public string fClinicalUseCode { get; set; }
        public string fClinicalUse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pharmacy_tClinicalUseDetails> Pharmacy_tClinicalUseDetails { get; set; }
    }
}
