//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomList()
        {
            this.Appointment_Room_Schedule = new HashSet<Appointment_Room_Schedule>();
            this.Schedule_ClinicInfo = new HashSet<Schedule_ClinicInfo>();
            this.Schedule_ClinicSchedule = new HashSet<Schedule_ClinicSchedule>();
            this.Schedule_WardNurseSchedule = new HashSet<Schedule_WardNurseSchedule>();
        }
    
        public int Room_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment_Room_Schedule> Appointment_Room_Schedule { get; set; }
        public virtual RoomTypeList RoomTypeList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_ClinicInfo> Schedule_ClinicInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_ClinicSchedule> Schedule_ClinicSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_WardNurseSchedule> Schedule_WardNurseSchedule { get; set; }
    }
}
