//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_ClinicInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule_ClinicInfo()
        {
            this.Appt_ClinicList = new HashSet<Appt_ClinicList>();
            this.Cases_Medical_Records = new HashSet<Cases_Medical_Records>();
            this.Schedule_NurseSchedule = new HashSet<Schedule_NurseSchedule>();
        }
    
        public int ClinicInfo_ID { get; set; }
        public int doctor_ID { get; set; }
        public int ClincRoom_ID { get; set; }
        public string date { get; set; }
        public int ClinicTime_ID { get; set; }
        public Nullable<int> LeaveStatus { get; set; }
        public Nullable<int> RegistrationLimit { get; set; }
        public Nullable<int> JumpStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appt_ClinicList> Appt_ClinicList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cases_Medical_Records> Cases_Medical_Records { get; set; }
        public virtual Member_EmployeeList Member_EmployeeList { get; set; }
        public virtual RoomList RoomList { get; set; }
        public virtual Schedule_ClinicTime Schedule_ClinicTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_NurseSchedule> Schedule_NurseSchedule { get; set; }
    }
}
