//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOrder()
        {
            this.tOrderDetail = new HashSet<tOrderDetail>();
        }
    
        public int Id { get; set; }
        public string fOrderId { get; set; }
        public System.DateTime fOrderDate { get; set; }
        public Nullable<System.DateTime> fCheckPayDate { get; set; }
        public Nullable<System.DateTime> fShipDate { get; set; }
        public Nullable<System.DateTime> fGetDate { get; set; }
        public int fShipPrice { get; set; }
        public int fOrderPrice { get; set; }
        public string fReceiverName { get; set; }
        public string fReceiverPhone { get; set; }
        public string fReceiverAddress { get; set; }
        public string fMemo { get; set; }
        public string fAccountFiveNumber { get; set; }
        public string fPayType { get; set; }
        public string fShipType { get; set; }
        public int fMemberId { get; set; }
        public Nullable<int> fCouponIdforAmount { get; set; }
        public Nullable<int> fCouponIdforPercent { get; set; }
        public Nullable<int> fCouponIdforShip { get; set; }
    
        public virtual Member_MemberList Member_MemberList { get; set; }
        public virtual tCoupon tCoupon { get; set; }
        public virtual tCoupon tCoupon1 { get; set; }
        public virtual tCoupon tCoupon2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrderDetail> tOrderDetail { get; set; }
    }
}
